table Products
	lineageTag: 121d5122-6cb5-4ef5-acfb-380d29170b14

	column 'Product Name'
		dataType: string
		lineageTag: ddea6c05-4482-40ce-8daa-c69b7ad61731
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 5f2c8da4-69cc-41ec-a78c-e1251c6d37c1
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: a46655c9-6d58-4449-9f56-5c2d01db2d20
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6fd4f925-59b8-4bc9-b46f-fc2e21b1731c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Weight (kg)'
		dataType: double
		lineageTag: 11669acc-f846-407e-9471-381816ecaf29
		summarizeBy: none
		sourceColumn: Weight (kg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Color
		dataType: string
		lineageTag: 19176369-c47a-4a27-bc36-e4190b1a6214
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: edf41a7b-6fee-4de4-9671-18898176789d
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	partition Products-5201ac24-ad57-45da-a92f-87e2762532dd = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\root\Desktop\PBI kurs\Week1\ElectronicsCompanyData.xlsx"), null, true),
				    Products_Sheet = Source{[Item="Products",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product Name", type text}, {"Brand", type text}, {"Subcategory", type text}, {"Category", type text}, {"Weight (kg)", type number}, {"Color", type text}, {"Manufacturer", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

